### ISSUE TITLE
Switch babel out for babel-core to work with babel 6?

### ISSUE THREAD

**Issue by oksas** [algolia/react-test-boilerplate#2]
First off, thanks for putting this boilerplate together; it was really helpful in teaching me how to get up and running with testing in React.

As I mentioned in [this](https://disqus.com/home/discussion/algoliablog/how_we_unit_test_react_components_using_expect_jsx/?utm_source=reply&utm_medium=email&utm_content=read_more#comment-2645985357) comment on the Algolia blog post on the subject, it seems that in order to work with the latest version of babel, the `babel-core` package should be used in place of `babel` inside `package.json`. I tried following along with the blog post and recreating this boilerplate with it, but npm told me it couldn't find `babel/register` as it was referenced in `mocha.opts`. I presume this has to do with changes between babel 5 and 6.

To fix the issue, I:
1. Used the `babel-core` package instead of `babel` in my `package.json`
2. Changed the first line of `mocha.opts` from `--compilers js:babel/register` to `--compilers js:babel-core/register`

Hope that's clear! I'm not entirely sure what the deal is between `babel` versus `babel-core` but for everything React-related (with webpack) I've been doing lately, I've been using `babel-core` and not `babel`, and that fixed the issue I was having here.

**Comment by vvo** [comment]
Thanks! Just updated the repo to work with babel6

**Comment by vvo** [comment]
Also updating the blogpost
